{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.prog.wezterm;
  loginStr = if pkgs.stdenv.isLinux then "" else " -l";
in
{
  options.prog = {
    wezterm.enable = lib.mkEnableOption "Enable wezterm";
    wezterm.package = lib.mkPackageOption pkgs "wezterm" { };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [
      pkgs.noto-fonts-cjk-sans
      pkgs.noto-fonts-color-emoji
      pkgs.iosevka
      pkgs.nerd-fonts.fira-code
      pkgs.fira-code
      pkgs.fira-code-symbols
      pkgs.fira-go
      pkgs.fira-math
      pkgs.ipafont
    ];

    prog.sesh.enable = true;

    programs.wezterm = {
      enable = true;
      package = cfg.package;
      enableBashIntegration = true;
      enableZshIntegration = true;
      extraConfig = ''
        local config = wezterm.config_builder()
        local act = wezterm.action

        config.font = wezterm.font_with_fallback {
            'Fira Code',
            'Fira Math',
            'Fira Code Symbol',
            'Noto Sans CJK JP',
            'FiraGO',
            'Iosevka',
            'IPAGothic',
        }

        config.enable_kitty_keyboard = true;

        config.enable_tab_bar = false;

        wezterm.on("update-status", function(window, pane)
            if wezterm.gui.screens().active.name == 'Microstep MAG321UX OLED' then
                window:set_config_overrides({dpi = 386})
            else
                window:set_config_overrides({dpi = 196})
            end
        end)

        config.default_prog = {
            '${pkgs.fish}/bin/fish',
            '-i',
            '-l',
            '-c', 
            'exec ${pkgs.sesh}/bin/sesh connect default'
        }

        -- Keybinds

        config.keys = {
          { key = '}', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '}', mods = 'SHIFT|SUPER', action = act.DisableDefaultAssignment },
          { key = '{', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '{', mods = 'SHIFT|SUPER', action = act.DisableDefaultAssignment },
          { key = 'z', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'x', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'w', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = 'w', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'v', mods = 'SUPER', action = act.PasteFrom 'Clipboard' },
          { key = 'v', mods = 'SHIFT|CTRL', action = act.PasteFrom 'Clipboard' },
          --{ key = 'v', mods = 'SUPER', action = act.DisableDefaultAssignment },
          --{ key = 'v', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'u', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 't', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = 't', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'r', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = 'r', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'q', mods = 'SUPER', action = act.QuitApplication },
          { key = 'q', mods = 'SHIFT|CTRL', action = act.QuitApplication },
          --{ key = 'q', mods = 'SUPER', action = act.DisableDefaultAssignment },
          --{ key = 'q', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'phys:Space', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'p', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'n', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = 'n', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'm', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = 'm', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'l', mods = 'SHIFT|CTRL', action = act.ShowDebugOverlay },
          { key = 'l', mods = 'ALT', action = act.ShowDebugOverlay },
          --{ key = 'l', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'k', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = 'k', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'h', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = 'h', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'f', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = 'f', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'c', mods = 'SUPER', action = act.CopyTo 'Clipboard' },
          { key = 'c', mods = 'SHIFT|CTRL', action = act.CopyTo 'Clipboard' },
          --{ key = 'c', mods = 'SUPER', action = act.DisableDefaultAssignment },
          --{ key = 'c', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '_', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '_', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '^', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '^', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = ']', mods = 'SHIFT|SUPER', action = act.DisableDefaultAssignment },
          { key = '\''', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = '\"', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = '\"', mods = 'ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = '[', mods = 'SHIFT|SUPER', action = act.DisableDefaultAssignment },
          { key = 'Z', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'Z', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'X', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'X', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'W', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'W', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'V', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'V', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'UpArrow', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'UpArrow', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'U', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'U', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'Tab', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'Tab', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'T', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'T', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'RightArrow', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'RightArrow', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'R', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'R', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'Q', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'Q', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'Paste', mods = 'NONE', action = act.DisableDefaultAssignment },
          { key = 'PageUp', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'PageUp', mods = 'SHIFT', action = act.DisableDefaultAssignment },
          { key = 'PageUp', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'PageDown', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'PageDown', mods = 'SHIFT', action = act.DisableDefaultAssignment },
          { key = 'PageDown', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'P', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'P', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'N', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'N', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'M', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'M', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'LeftArrow', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'LeftArrow', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'L', mods = 'SHIFT|CTRL', action = act.ShowDebugOverlay },
          --{ key = 'L', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'L', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'K', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'K', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'H', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'H', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'F', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'F', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = 'Enter', mods = 'ALT', action = act.DisableDefaultAssignment },
          { key = 'DownArrow', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'DownArrow', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'Copy', mods = 'NONE', action = act.DisableDefaultAssignment },
          { key = 'C', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = 'C', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '@', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '@', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '=', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '=', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '=', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '9', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '9', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '8', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '8', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '7', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '7', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '6', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '6', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '5', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '5', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '5', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = '4', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '4', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '3', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '3', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '2', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '2', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '1', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '1', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '0', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '0', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '0', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '-', mods = 'SUPER', action = act.DisableDefaultAssignment },
          { key = '-', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '-', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '+', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '+', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '*', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '*', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = ')', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = ')', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '(', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '(', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '&', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '&', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '%', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '%', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = '%', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '%', mods = 'ALT|CTRL', action = act.DisableDefaultAssignment },
          { key = '$', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '$', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '#', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '#', mods = 'CTRL', action = act.DisableDefaultAssignment },
          { key = '!', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
          { key = '!', mods = 'CTRL', action = act.DisableDefaultAssignment },
          --{ key = '}', mods = 'SUPER', action = act.ActivateTabRelative(1) },
          --{ key = '}', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(1) },
          --{ key = '{', mods = 'SUPER', action = act.ActivateTabRelative(-1) },
          --{ key = '{', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(-1) },
          --{ key = 'z', mods = 'SHIFT|CTRL', action = act.TogglePaneZoomState },
          --{ key = 'x', mods = 'SHIFT|CTRL', action = act.ActivateCopyMode },
          --{ key = 'w', mods = 'SUPER', action = act.CloseCurrentTab{ confirm = true } },
          --{ key = 'w', mods = 'SHIFT|CTRL', action = act.CloseCurrentTab{ confirm = true } },
          --{ key = 'v', mods = 'SUPER', action = act.PasteFrom 'Clipboard' },
          --{ key = 'v', mods = 'SHIFT|CTRL', action = act.PasteFrom 'Clipboard' },
          --{ key = 'u', mods = 'SHIFT|CTRL', action = act.CharSelect{ copy_on_select = true, copy_to =  'ClipboardAndPrimarySelection' } },
          --{ key = 't', mods = 'SUPER', action = act.SpawnTab 'CurrentPaneDomain' },
          --{ key = 't', mods = 'SHIFT|CTRL', action = act.SpawnTab 'CurrentPaneDomain' },
          --{ key = 'r', mods = 'SUPER', action = act.ReloadConfiguration },
          --{ key = 'r', mods = 'SHIFT|CTRL', action = act.ReloadConfiguration },
          --{ key = 'q', mods = 'SUPER', action = act.QuitApplication },
          --{ key = 'q', mods = 'SHIFT|CTRL', action = act.QuitApplication },
          --{ key = 'phys:Space', mods = 'SHIFT|CTRL', action = act.QuickSelect },
          --{ key = 'p', mods = 'SHIFT|CTRL', action = act.ActivateCommandPalette },
          --{ key = 'n', mods = 'SUPER', action = act.SpawnWindow },
          --{ key = 'n', mods = 'SHIFT|CTRL', action = act.SpawnWindow },
          --{ key = 'm', mods = 'SUPER', action = act.Hide },
          --{ key = 'm', mods = 'SHIFT|CTRL', action = act.Hide },
          --{ key = 'l', mods = 'SHIFT|CTRL', action = act.ShowDebugOverlay },
          --{ key = 'k', mods = 'SUPER', action = act.ClearScrollback 'ScrollbackOnly' },
          --{ key = 'k', mods = 'SHIFT|CTRL', action = act.ClearScrollback 'ScrollbackOnly' },
          --{ key = 'h', mods = 'SUPER', action = act.HideApplication },
          --{ key = 'h', mods = 'SHIFT|CTRL', action = act.HideApplication },
          --{ key = 'f', mods = 'SUPER', action = act.Search 'CurrentSelectionOrEmptyString' },
          --{ key = 'f', mods = 'SHIFT|CTRL', action = act.Search 'CurrentSelectionOrEmptyString' },
          --{ key = 'c', mods = 'SUPER', action = act.CopyTo 'Clipboard' },
          --{ key = 'c', mods = 'SHIFT|CTRL', action = act.CopyTo 'Clipboard' },
          --{ key = '_', mods = 'SHIFT|CTRL', action = act.DecreaseFontSize },
          --{ key = '_', mods = 'CTRL', action = act.DecreaseFontSize },
          --{ key = '^', mods = 'SHIFT|CTRL', action = act.ActivateTab(5) },
          --{ key = '^', mods = 'CTRL', action = act.ActivateTab(5) },
          --{ key = ']', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(1) },
          --{ key = '\''', mods = 'SHIFT|ALT|CTRL', action = act.SplitVertical{ domain =  'CurrentPaneDomain' } },
          --{ key = '\"', mods = 'SHIFT|ALT|CTRL', action = act.SplitVertical{ domain =  'CurrentPaneDomain' } },
          --{ key = '\"', mods = 'ALT|CTRL', action = act.SplitVertical{ domain =  'CurrentPaneDomain' } },
          --{ key = '[', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(-1) },
          --{ key = 'Z', mods = 'SHIFT|CTRL', action = act.TogglePaneZoomState },
          --{ key = 'Z', mods = 'CTRL', action = act.TogglePaneZoomState },
          --{ key = 'X', mods = 'SHIFT|CTRL', action = act.ActivateCopyMode },
          --{ key = 'X', mods = 'CTRL', action = act.ActivateCopyMode },
          --{ key = 'W', mods = 'SHIFT|CTRL', action = act.CloseCurrentTab{ confirm = true } },
          --{ key = 'W', mods = 'CTRL', action = act.CloseCurrentTab{ confirm = true } },
          --{ key = 'V', mods = 'SHIFT|CTRL', action = act.PasteFrom 'Clipboard' },
          --{ key = 'V', mods = 'CTRL', action = act.PasteFrom 'Clipboard' },
          --{ key = 'UpArrow', mods = 'SHIFT|CTRL', action = act.ActivatePaneDirection 'Up' },
          --{ key = 'UpArrow', mods = 'SHIFT|ALT|CTRL', action = act.AdjustPaneSize{ 'Up', 1 } },
          --{ key = 'U', mods = 'SHIFT|CTRL', action = act.CharSelect{ copy_on_select = true, copy_to =  'ClipboardAndPrimarySelection' } },
          --{ key = 'U', mods = 'CTRL', action = act.CharSelect{ copy_on_select = true, copy_to =  'ClipboardAndPrimarySelection' } },
          --{ key = 'Tab', mods = 'SHIFT|CTRL', action = act.ActivateTabRelative(-1) },
          --{ key = 'Tab', mods = 'CTRL', action = act.ActivateTabRelative(1) },
          --{ key = 'T', mods = 'SHIFT|CTRL', action = act.SpawnTab 'CurrentPaneDomain' },
          --{ key = 'T', mods = 'CTRL', action = act.SpawnTab 'CurrentPaneDomain' },
          --{ key = 'RightArrow', mods = 'SHIFT|CTRL', action = act.ActivatePaneDirection 'Right' },
          --{ key = 'RightArrow', mods = 'SHIFT|ALT|CTRL', action = act.AdjustPaneSize{ 'Right', 1 } },
          --{ key = 'R', mods = 'SHIFT|CTRL', action = act.ReloadConfiguration },
          --{ key = 'R', mods = 'CTRL', action = act.ReloadConfiguration },
          --{ key = 'Q', mods = 'SHIFT|CTRL', action = act.QuitApplication },
          --{ key = 'Q', mods = 'CTRL', action = act.QuitApplication },
          --{ key = 'Paste', mods = 'NONE', action = act.PasteFrom 'Clipboard' },
          --{ key = 'PageUp', mods = 'SHIFT|CTRL', action = act.MoveTabRelative(-1) },
          --{ key = 'PageUp', mods = 'SHIFT', action = act.ScrollByPage(-1) },
          --{ key = 'PageUp', mods = 'CTRL', action = act.ActivateTabRelative(-1) },
          --{ key = 'PageDown', mods = 'SHIFT|CTRL', action = act.MoveTabRelative(1) },
          --{ key = 'PageDown', mods = 'SHIFT', action = act.ScrollByPage(1) },
          --{ key = 'PageDown', mods = 'CTRL', action = act.ActivateTabRelative(1) },
          --{ key = 'P', mods = 'SHIFT|CTRL', action = act.ActivateCommandPalette },
          --{ key = 'P', mods = 'CTRL', action = act.ActivateCommandPalette },
          --{ key = 'N', mods = 'SHIFT|CTRL', action = act.SpawnWindow },
          --{ key = 'N', mods = 'CTRL', action = act.SpawnWindow },
          --{ key = 'M', mods = 'SHIFT|CTRL', action = act.Hide },
          --{ key = 'M', mods = 'CTRL', action = act.Hide },
          --{ key = 'LeftArrow', mods = 'SHIFT|CTRL', action = act.ActivatePaneDirection 'Left' },
          --{ key = 'LeftArrow', mods = 'SHIFT|ALT|CTRL', action = act.AdjustPaneSize{ 'Left', 1 } },
          --{ key = 'L', mods = 'SHIFT|CTRL', action = act.ShowDebugOverlay },
          --{ key = 'L', mods = 'CTRL', action = act.ShowDebugOverlay },
          --{ key = 'K', mods = 'SHIFT|CTRL', action = act.ClearScrollback 'ScrollbackOnly' },
          --{ key = 'K', mods = 'CTRL', action = act.ClearScrollback 'ScrollbackOnly' },
          --{ key = 'H', mods = 'SHIFT|CTRL', action = act.HideApplication },
          --{ key = 'H', mods = 'CTRL', action = act.HideApplication },
          --{ key = 'F', mods = 'SHIFT|CTRL', action = act.Search 'CurrentSelectionOrEmptyString' },
          --{ key = 'F', mods = 'CTRL', action = act.Search 'CurrentSelectionOrEmptyString' },
          --{ key = 'Enter', mods = 'ALT', action = act.ToggleFullScreen },
          --{ key = 'DownArrow', mods = 'SHIFT|CTRL', action = act.ActivatePaneDirection 'Down' },
          --{ key = 'DownArrow', mods = 'SHIFT|ALT|CTRL', action = act.AdjustPaneSize{ 'Down', 1 } },
          --{ key = 'Copy', mods = 'NONE', action = act.CopyTo 'Clipboard' },
          --{ key = 'C', mods = 'SHIFT|CTRL', action = act.CopyTo 'Clipboard' },
          --{ key = 'C', mods = 'CTRL', action = act.CopyTo 'Clipboard' },
          --{ key = '@', mods = 'SHIFT|CTRL', action = act.ActivateTab(1) },
          --{ key = '@', mods = 'CTRL', action = act.ActivateTab(1) },
          --{ key = '=', mods = 'SUPER', action = act.IncreaseFontSize },
          --{ key = '=', mods = 'SHIFT|CTRL', action = act.IncreaseFontSize },
          --{ key = '=', mods = 'CTRL', action = act.IncreaseFontSize },
          --{ key = '9', mods = 'SUPER', action = act.ActivateTab(-1) },
          --{ key = '9', mods = 'SHIFT|CTRL', action = act.ActivateTab(-1) },
          --{ key = '8', mods = 'SUPER', action = act.ActivateTab(7) },
          --{ key = '8', mods = 'SHIFT|CTRL', action = act.ActivateTab(7) },
          --{ key = '7', mods = 'SUPER', action = act.ActivateTab(6) },
          --{ key = '7', mods = 'SHIFT|CTRL', action = act.ActivateTab(6) },
          --{ key = '6', mods = 'SUPER', action = act.ActivateTab(5) },
          --{ key = '6', mods = 'SHIFT|CTRL', action = act.ActivateTab(5) },
          --{ key = '5', mods = 'SUPER', action = act.ActivateTab(4) },
          --{ key = '5', mods = 'SHIFT|CTRL', action = act.ActivateTab(4) },
          --{ key = '5', mods = 'SHIFT|ALT|CTRL', action = act.SplitHorizontal{ domain =  'CurrentPaneDomain' } },
          --{ key = '4', mods = 'SUPER', action = act.ActivateTab(3) },
          --{ key = '4', mods = 'SHIFT|CTRL', action = act.ActivateTab(3) },
          --{ key = '3', mods = 'SUPER', action = act.ActivateTab(2) },
          --{ key = '3', mods = 'SHIFT|CTRL', action = act.ActivateTab(2) },
          --{ key = '2', mods = 'SUPER', action = act.ActivateTab(1) },
          --{ key = '2', mods = 'SHIFT|CTRL', action = act.ActivateTab(1) },
          --{ key = '1', mods = 'SUPER', action = act.ActivateTab(0) },
          --{ key = '1', mods = 'SHIFT|CTRL', action = act.ActivateTab(0) },
          --{ key = '0', mods = 'SUPER', action = act.ResetFontSize },
          --{ key = '0', mods = 'SHIFT|CTRL', action = act.ResetFontSize },
          --{ key = '0', mods = 'CTRL', action = act.ResetFontSize },
          --{ key = '-', mods = 'SUPER', action = act.DecreaseFontSize },
          --{ key = '-', mods = 'SHIFT|CTRL', action = act.DecreaseFontSize },
          --{ key = '-', mods = 'CTRL', action = act.DecreaseFontSize },
          --{ key = '+', mods = 'SHIFT|CTRL', action = act.IncreaseFontSize },
          --{ key = '+', mods = 'CTRL', action = act.IncreaseFontSize },
          --{ key = '*', mods = 'SHIFT|CTRL', action = act.ActivateTab(7) },
          --{ key = '*', mods = 'CTRL', action = act.ActivateTab(7) },
          --{ key = ')', mods = 'SHIFT|CTRL', action = act.ResetFontSize },
          --{ key = ')', mods = 'CTRL', action = act.ResetFontSize },
          --{ key = '(', mods = 'SHIFT|CTRL', action = act.ActivateTab(-1) },
          --{ key = '(', mods = 'CTRL', action = act.ActivateTab(-1) },
          --{ key = '&', mods = 'SHIFT|CTRL', action = act.ActivateTab(6) },
          --{ key = '&', mods = 'CTRL', action = act.ActivateTab(6) },
          --{ key = '%', mods = 'SHIFT|CTRL', action = act.ActivateTab(4) },
          --{ key = '%', mods = 'SHIFT|ALT|CTRL', action = act.SplitHorizontal{ domain =  'CurrentPaneDomain' } },
          --{ key = '%', mods = 'CTRL', action = act.ActivateTab(4) },
          --{ key = '%', mods = 'ALT|CTRL', action = act.SplitHorizontal{ domain =  'CurrentPaneDomain' } },
          --{ key = '$', mods = 'SHIFT|CTRL', action = act.ActivateTab(3) },
          --{ key = '$', mods = 'CTRL', action = act.ActivateTab(3) },
          --{ key = '#', mods = 'SHIFT|CTRL', action = act.ActivateTab(2) },
          --{ key = '#', mods = 'CTRL', action = act.ActivateTab(2) },
          --{ key = '!', mods = 'SHIFT|CTRL', action = act.ActivateTab(0) },
          --{ key = '!', mods = 'CTRL', action = act.ActivateTab(0) },
        }

        config.key_tables = {
          copy_mode = {
            { key = 'y', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'w', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'v', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'v', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'u', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 't', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'q', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'o', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'm', mods = 'ALT', action = act.DisableDefaultAssignment },
            { key = 'l', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'k', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'j', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'h', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'g', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'g', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'f', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'f', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'f', mods = 'ALT', action = act.DisableDefaultAssignment },
            { key = 'e', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'd', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'c', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'b', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'b', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'b', mods = 'ALT', action = act.DisableDefaultAssignment },
            { key = '^', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = '^', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'V', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'V', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'UpArrow', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'Tab', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'Tab', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'T', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'T', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'Space', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'RightArrow', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'RightArrow', mods = 'ALT', action = act.DisableDefaultAssignment },
            { key = 'PageUp', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'PageDown', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'O', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'O', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'M', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'M', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'LeftArrow', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'LeftArrow', mods = 'ALT', action = act.DisableDefaultAssignment },
            { key = 'L', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'L', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'Home', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'H', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'H', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'G', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'G', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'F', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = 'F', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'Escape', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'Enter', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'End', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'DownArrow', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = ';', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = '0', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = ',', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = '$', mods = 'SHIFT', action = act.DisableDefaultAssignment },
            { key = '$', mods = 'NONE', action = act.DisableDefaultAssignment },
            --{ key = 'y', mods = 'NONE', action = act.Multiple{ { CopyTo =  'ClipboardAndPrimarySelection' }, { Multiple = { 'ScrollToBottom', { CopyMode =  'Close' } } } } },
            --{ key = 'w', mods = 'NONE', action = act.CopyMode 'MoveForwardWord' },
            --{ key = 'v', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Cell' } },
            --{ key = 'v', mods = 'CTRL', action = act.CopyMode{ SetSelectionMode =  'Block' } },
            --{ key = 'u', mods = 'CTRL', action = act.CopyMode{ MoveByPage = (-0.5) } },
            --{ key = 't', mods = 'NONE', action = act.CopyMode{ JumpForward = { prev_char = true } } },
            --{ key = 'q', mods = 'NONE', action = act.Multiple{ 'ScrollToBottom', { CopyMode =  'Close' } } },
            --{ key = 'o', mods = 'NONE', action = act.CopyMode 'MoveToSelectionOtherEnd' },
            --{ key = 'm', mods = 'ALT', action = act.CopyMode 'MoveToStartOfLineContent' },
            --{ key = 'l', mods = 'NONE', action = act.CopyMode 'MoveRight' },
            --{ key = 'k', mods = 'NONE', action = act.CopyMode 'MoveUp' },
            --{ key = 'j', mods = 'NONE', action = act.CopyMode 'MoveDown' },
            --{ key = 'h', mods = 'NONE', action = act.CopyMode 'MoveLeft' },
            --{ key = 'g', mods = 'NONE', action = act.CopyMode 'MoveToScrollbackTop' },
            --{ key = 'g', mods = 'CTRL', action = act.Multiple{ 'ScrollToBottom', { CopyMode =  'Close' } } },
            --{ key = 'f', mods = 'NONE', action = act.CopyMode{ JumpForward = { prev_char = false } } },
            --{ key = 'f', mods = 'CTRL', action = act.CopyMode 'PageDown' },
            --{ key = 'f', mods = 'ALT', action = act.CopyMode 'MoveForwardWord' },
            --{ key = 'e', mods = 'NONE', action = act.CopyMode 'MoveForwardWordEnd' },
            --{ key = 'd', mods = 'CTRL', action = act.CopyMode{ MoveByPage = (0.5) } },
            --{ key = 'c', mods = 'CTRL', action = act.Multiple{ 'ScrollToBottom', { CopyMode =  'Close' } } },
            --{ key = 'b', mods = 'NONE', action = act.CopyMode 'MoveBackwardWord' },
            --{ key = 'b', mods = 'CTRL', action = act.CopyMode 'PageUp' },
            --{ key = 'b', mods = 'ALT', action = act.CopyMode 'MoveBackwardWord' },
            --{ key = '^', mods = 'SHIFT', action = act.CopyMode 'MoveToStartOfLineContent' },
            --{ key = '^', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLineContent' },
            --{ key = 'V', mods = 'SHIFT', action = act.CopyMode{ SetSelectionMode =  'Line' } },
            --{ key = 'V', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Line' } },
            --{ key = 'UpArrow', mods = 'NONE', action = act.CopyMode 'MoveUp' },
            --{ key = 'Tab', mods = 'SHIFT', action = act.CopyMode 'MoveBackwardWord' },
            --{ key = 'Tab', mods = 'NONE', action = act.CopyMode 'MoveForwardWord' },
            --{ key = 'T', mods = 'SHIFT', action = act.CopyMode{ JumpBackward = { prev_char = true } } },
            --{ key = 'T', mods = 'NONE', action = act.CopyMode{ JumpBackward = { prev_char = true } } },
            --{ key = 'Space', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Cell' } },
            --{ key = 'RightArrow', mods = 'NONE', action = act.CopyMode 'MoveRight' },
            --{ key = 'RightArrow', mods = 'ALT', action = act.CopyMode 'MoveForwardWord' },
            --{ key = 'PageUp', mods = 'NONE', action = act.CopyMode 'PageUp' },
            --{ key = 'PageDown', mods = 'NONE', action = act.CopyMode 'PageDown' },
            --{ key = 'O', mods = 'SHIFT', action = act.CopyMode 'MoveToSelectionOtherEndHoriz' },
            --{ key = 'O', mods = 'NONE', action = act.CopyMode 'MoveToSelectionOtherEndHoriz' },
            --{ key = 'M', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportMiddle' },
            --{ key = 'M', mods = 'NONE', action = act.CopyMode 'MoveToViewportMiddle' },
            --{ key = 'LeftArrow', mods = 'NONE', action = act.CopyMode 'MoveLeft' },
            --{ key = 'LeftArrow', mods = 'ALT', action = act.CopyMode 'MoveBackwardWord' },
            --{ key = 'L', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportBottom' },
            --{ key = 'L', mods = 'NONE', action = act.CopyMode 'MoveToViewportBottom' },
            --{ key = 'Home', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLine' },
            --{ key = 'H', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportTop' },
            --{ key = 'H', mods = 'NONE', action = act.CopyMode 'MoveToViewportTop' },
            --{ key = 'G', mods = 'SHIFT', action = act.CopyMode 'MoveToScrollbackBottom' },
            --{ key = 'G', mods = 'NONE', action = act.CopyMode 'MoveToScrollbackBottom' },
            --{ key = 'F', mods = 'SHIFT', action = act.CopyMode{ JumpBackward = { prev_char = false } } },
            --{ key = 'F', mods = 'NONE', action = act.CopyMode{ JumpBackward = { prev_char = false } } },
            --{ key = 'Escape', mods = 'NONE', action = act.Multiple{ 'ScrollToBottom', { CopyMode =  'Close' } } },
            --{ key = 'Enter', mods = 'NONE', action = act.CopyMode 'MoveToStartOfNextLine' },
            --{ key = 'End', mods = 'NONE', action = act.CopyMode 'MoveToEndOfLineContent' },
            --{ key = 'DownArrow', mods = 'NONE', action = act.CopyMode 'MoveDown' },
            --{ key = ';', mods = 'NONE', action = act.CopyMode 'JumpAgain' },
            --{ key = '0', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLine' },
            --{ key = ',', mods = 'NONE', action = act.CopyMode 'JumpReverse' },
            --{ key = '$', mods = 'SHIFT', action = act.CopyMode 'MoveToEndOfLineContent' },
            --{ key = '$', mods = 'NONE', action = act.CopyMode 'MoveToEndOfLineContent' },
          },

          search_mode = {
            { key = 'u', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'r', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'p', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'n', mods = 'CTRL', action = act.DisableDefaultAssignment },
            { key = 'UpArrow', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'PageUp', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'PageDown', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'Escape', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'Enter', mods = 'NONE', action = act.DisableDefaultAssignment },
            { key = 'DownArrow', mods = 'NONE', action = act.DisableDefaultAssignment },
            --{ key = 'u', mods = 'CTRL', action = act.CopyMode 'ClearPattern' },
            --{ key = 'r', mods = 'CTRL', action = act.CopyMode 'CycleMatchType' },
            --{ key = 'p', mods = 'CTRL', action = act.CopyMode 'PriorMatch' },
            --{ key = 'n', mods = 'CTRL', action = act.CopyMode 'NextMatch' },
            --{ key = 'UpArrow', mods = 'NONE', action = act.CopyMode 'PriorMatch' },
            --{ key = 'PageUp', mods = 'NONE', action = act.CopyMode 'PriorMatchPage' },
            --{ key = 'PageDown', mods = 'NONE', action = act.CopyMode 'NextMatchPage' },
            --{ key = 'Escape', mods = 'NONE', action = act.CopyMode 'Close' },
            --{ key = 'Enter', mods = 'NONE', action = act.CopyMode 'PriorMatch' },
            --{ key = 'DownArrow', mods = 'NONE', action = act.CopyMode 'NextMatch' },
          },
        }

        return config
      '';
    };
  };
}
