#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/source -mindepth 1 -maxdepth 5 -path "*.git" -type d\
        -exec dirname {} \; 2> /dev/null ;\
    find ~ -maxdepth 2 -path "*.git" -type d\
        -exec dirname {} \; 2> /dev/null ;\ 
    find /etc/ -maxdepth 3 -path "*.git" -path "*nix*" -type d\
        -exec dirname {} \; 2> /dev/null\
    | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
